#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\armor.bof
BOFS = bodyarmor.bof shield.bof helmet.bof pants.bof shirt.bof gloves.bof \
   trinket.bof

!include $(KODDIR)\kod.mak
