#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\stroke.bof
BOFS = slash.bof unarmed.bof thrust.bof fire.bof stab.bof strike.bof monsterstroke.bof

!include $(KODDIR)\kod.mak
