#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\splashspel.bof
BOFS = blasfire.bof exfrost.bof illwound.bof shokfury.bof splsacid.bof vampdrn.bof

!include $(KODDIR)\kod.mak
