#
# Makefile for compiling the Blakod
#

!include $(TOPDIR)\common.mak

DEPEND = ..\monsterweapon.bof
BOFS = claws.bof fangs.bof branch.bof stinger.bof secretions.bof\
         trident.bof pickaxe.bof

!include $(KODDIR)\kod.mak
